### ISSUE TITLE
Segmentation fault when using reduction operator

### ISSUE THREAD

**Issue by danlm** [pahihu/apl11#1]
Compiled on 64-bit Ubuntu 18.04 using gcc.
Using the reduction operator leads to a segmentation fault:
```
a p l \ 1 1
12 nov 1992

clear ws
	+/1 2 3

Program received signal SIGSEGV, Segmentation fault.
0x000055555555e145 in red1 (param=0xffffde8c) at a6.c:97
97		dp = param[0];
```
Relevant code line:
https://github.com/pahihu/apl11/blob/fe1fa8a73c07e3631fcf1b3b0498f47204269c61/a6.c#L97

The openAPL version does not encounter this problem:
[    dp += access() + (idx.dimk - 1) * idx.delk;](https://github.com/PlanetAPL/openAPL/blob/92358c7d1f66593726e661bf9d8d5a812c08c25d/apl11/oper_monadic/ex_red.c#L104)

**Comment by pahihu** [comment]
Yep, I know.
If you check the makefile, all targets are 32bit. It is intentional.
openAPL is a great piece of software.

pahihu

===> file apl
apl: Mach-O executable i386

22:02:59 - Tue Apr 14] ~/src/github/apl11 
===> ./apl
a p l \ 1 1
12 nov 1992

clear ws
	+/1 2 3
 6
	)off

**Comment by danlm** [comment]
Fair enough :+1:  It compiled when I changed the target to "-march=x86-64', so I decided to press my luck.
